Traceback (most recent call last):
  File "/opt/anaconda3/envs/book/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/book/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/book/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/book/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def read_platemap_str(platemap_str: str) -> pd.DataFrame:
    platemap = pd.read_table(io.StringIO(platemap_str), index_col=0)
    platemap.index.name = "Row"
    platemap = platemap.reset_index().melt(id_vars=["Row"], var_name="Column", value_name="Construct")
    
    platemap["Column"] = platemap["Column"].astype(int)
    platemap["Well"] = platemap.apply(lambda well: f"{well['Row']}:{well['Column']}", axis=1)
    platemap = platemap.rename(columns={"Construct": "Label"})
    platemap = platemap.dropna()
    return platemap

def read_platemap_excel(platemap_path: str) -> pd.DataFrame:
    """
    Use like this:

    
    > platemap_path = "path/to/platemap.xlsx"
    > platemap = read_platemap_excel(platemap_path)
    > platemap.head()
    """
    platemap = pd.read_excel(platemap_path)
    platemap.fillna(value=0, inplace=True)
    platemap['Row'] = platemap['Well'].apply(lambda s: s.split(":")[0])
    platemap['Column'] = platemap['Well'].apply(lambda s: s.split(":")[1]).astype(int)

    return platemap

# LOAD YOUR PLATEMAP HERE
platemap = read_platemap_excel(
    f"data/{date}-platemap.xlsx"
)
platemap.head()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 29[0m
[1;32m     26[0m     [38;5;28;01mreturn[39;00m platemap
[1;32m     28[0m [38;5;66;03m# LOAD YOUR PLATEMAP HERE[39;00m
[0;32m---> 29[0m platemap [38;5;241m=[39m [43mread_platemap_excel[49m[43m([49m
[1;32m     30[0m [43m    [49m[38;5;124;43mf[39;49m[38;5;124;43m"[39;49m[38;5;124;43mdata/[39;49m[38;5;132;43;01m{[39;49;00m[43mdate[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m-platemap.xlsx[39;49m[38;5;124;43m"[39;49m
[1;32m     31[0m [43m)[49m
[1;32m     32[0m platemap[38;5;241m.[39mhead()

Cell [0;32mIn[2], line 21[0m, in [0;36mread_platemap_excel[0;34m(platemap_path)[0m
[1;32m     12[0m [38;5;28;01mdef[39;00m [38;5;21mread_platemap_excel[39m(platemap_path: [38;5;28mstr[39m) [38;5;241m-[39m[38;5;241m>[39m pd[38;5;241m.[39mDataFrame:
[1;32m     13[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m     14[0m [38;5;124;03m    Use like this:[39;00m
[1;32m     15[0m 
[0;32m   (...)[0m
[1;32m     19[0m [38;5;124;03m    > platemap.head()[39;00m
[1;32m     20[0m [38;5;124;03m    """[39;00m
[0;32m---> 21[0m     platemap [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_excel[49m[43m([49m[43mplatemap_path[49m[43m)[49m
[1;32m     22[0m     platemap[38;5;241m.[39mfillna(value[38;5;241m=[39m[38;5;241m0[39m, inplace[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     23[0m     platemap[[38;5;124m'[39m[38;5;124mRow[39m[38;5;124m'[39m] [38;5;241m=[39m platemap[[38;5;124m'[39m[38;5;124mWell[39m[38;5;124m'[39m][38;5;241m.[39mapply([38;5;28;01mlambda[39;00m s: s[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m:[39m[38;5;124m"[39m)[[38;5;241m0[39m])

File [0;32m/opt/anaconda3/envs/book/lib/python3.12/site-packages/pandas/io/excel/_base.py:495[0m, in [0;36mread_excel[0;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)[0m
[1;32m    493[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[1;32m    494[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m--> 495[0m     io [38;5;241m=[39m [43mExcelFile[49m[43m([49m
[1;32m    496[0m [43m        [49m[43mio[49m[43m,[49m
[1;32m    497[0m [43m        [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m
[1;32m    498[0m [43m        [49m[43mengine[49m[38;5;241;43m=[39;49m[43mengine[49m[43m,[49m
[1;32m    499[0m [43m        [49m[43mengine_kwargs[49m[38;5;241;43m=[39;49m[43mengine_kwargs[49m[43m,[49m
[1;32m    500[0m [43m    [49m[43m)[49m
[1;32m    501[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[1;32m    502[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    503[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[1;32m    504[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[1;32m    505[0m     )

File [0;32m/opt/anaconda3/envs/book/lib/python3.12/site-packages/pandas/io/excel/_base.py:1550[0m, in [0;36mExcelFile.__init__[0;34m(self, path_or_buffer, engine, storage_options, engine_kwargs)[0m
[1;32m   1548[0m     ext [38;5;241m=[39m [38;5;124m"[39m[38;5;124mxls[39m[38;5;124m"[39m
[1;32m   1549[0m [38;5;28;01melse[39;00m:
[0;32m-> 1550[0m     ext [38;5;241m=[39m [43minspect_excel_format[49m[43m([49m
[1;32m   1551[0m [43m        [49m[43mcontent_or_path[49m[38;5;241;43m=[39;49m[43mpath_or_buffer[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m
[1;32m   1552[0m [43m    [49m[43m)[49m
[1;32m   1553[0m     [38;5;28;01mif[39;00m ext [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1554[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1555[0m             [38;5;124m"[39m[38;5;124mExcel file format cannot be determined, you must specify [39m[38;5;124m"[39m
[1;32m   1556[0m             [38;5;124m"[39m[38;5;124man engine manually.[39m[38;5;124m"[39m
[1;32m   1557[0m         )

File [0;32m/opt/anaconda3/envs/book/lib/python3.12/site-packages/pandas/io/excel/_base.py:1402[0m, in [0;36minspect_excel_format[0;34m(content_or_path, storage_options)[0m
[1;32m   1399[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(content_or_path, [38;5;28mbytes[39m):
[1;32m   1400[0m     content_or_path [38;5;241m=[39m BytesIO(content_or_path)
[0;32m-> 1402[0m [38;5;28;01mwith[39;00m [43mget_handle[49m[43m([49m
[1;32m   1403[0m [43m    [49m[43mcontent_or_path[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m[43m [49m[43mis_text[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m
[1;32m   1404[0m [43m[49m[43m)[49m [38;5;28;01mas[39;00m handle:
[1;32m   1405[0m     stream [38;5;241m=[39m handle[38;5;241m.[39mhandle
[1;32m   1406[0m     stream[38;5;241m.[39mseek([38;5;241m0[39m)

File [0;32m/opt/anaconda3/envs/book/lib/python3.12/site-packages/pandas/io/common.py:882[0m, in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    873[0m         handle [38;5;241m=[39m [38;5;28mopen[39m(
[1;32m    874[0m             handle,
[1;32m    875[0m             ioargs[38;5;241m.[39mmode,
[0;32m   (...)[0m
[1;32m    878[0m             newline[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m,
[1;32m    879[0m         )
[1;32m    880[0m     [38;5;28;01melse[39;00m:
[1;32m    881[0m         [38;5;66;03m# Binary mode[39;00m
[0;32m--> 882[0m         handle [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mhandle[49m[43m,[49m[43m [49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m)[49m
[1;32m    883[0m     handles[38;5;241m.[39mappend(handle)
[1;32m    885[0m [38;5;66;03m# Convert BytesIO or file objects passed with an encoding[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/20240916-platemap.xlsx'

